#name of the plugin
name: "PingEnforcer"
#description of the plugin
description: "Enforces player ping limits based on server average"
#the version string for the plugin
version: "1.0.0"
#backend which the plugin can run under "BF3" and "VU" allowed
#"BF3" plugins will run under BF3 and VU
backend: "BF3"
#plugin entry point
entry: "index.js"
vars:
  - name: "timer"
    description: "Time between ping checks (in seconds)"
    default: 60
    type: "number"
  - name: "savePing"
    description: "Minimum safe ping value (players with a lower ping will never be kicked)"
    type: "number"
    default: 100
  - name: "pingMulti"
    description: "Multiplikator (average ping * multiplikator = max ping)" 
    type: "number"
    default: 1.5
  - name: "PassiveMode"
    description: "Runs the logic without actually enforcing a kick (useful for tweaking settings). See plugin logs for actions."
    type: "boolean"
    default: true